### ISSUE TITLE
issue about training dataset

### ISSUE THREAD

**Issue by ZhixiuYe** [SharmisthaJat/RE-DS-Word-Attention-Models#1]
Hello,
In file `Riedel/train.txt`, there are 570088 sentences, which is inconsistent with the dataset used by (Lin et al. 2016). In (Lin et al. 2016), there are 522611 sentences. And there are overlaps in entity pairs between training and test sentences, which is conflict with the held-out evaluation.
Why is this so?
Or do I misunderstand something about the dataset?

**Comment by SharmisthaJat** [comment]
Hi, 

Thanks for pointing this out. We were using the dataset provided by Lin et al. 2016 public git repository. Link: https://github.com/thunlp/NRE . The dataset was downloaded sometime back and I notice that they have now updated the dataset some 2 months back. The reason to use their dataset with the overlap was, to help replicate their settings, as we could never reach the curves they plotted in the original paper using their own code. I will update the data in our repo soon. 

Thanks,
Sharmistha
