### ISSUE TITLE
where is the <word embedding file name> file?

### ISSUE THREAD

**Issue by loveJasmine** [SharmisthaJat/RE-DS-Word-Attention-Models#2]

**Comment by SharmisthaJat** [comment]
In data folder.

**Comment by loveJasmine** [comment]
mldl@ub1604:~/ub16_prj/RE-DS-Word-Attention-Models/Codes/Models$ python BGWA.py ../../Data/GIDS  train.tsv test.tsv dev.tsv vec.bin 
Please Note That CUDA is required for the model to run
True
result dir=BGWA/
Traceback (most recent call last):
  File "BGWA.py", line 654, in <module>
    test = cPickle.load(open(inputdir+sys.argv[3]))
cPickle.UnpicklingError: invalid load key, '/'.

**Comment by SharmisthaJat** [comment]
You have missed the preprocessing step. Please follow instructions in the README

Run command example after preprocessing data:
python PCNN.py ../Preprocess train_final.p test_final.p dev_final.p Wv.p
