### ISSUE TITLE
what is the auc of model BGWA?

### ISSUE THREAD

**Issue by zhoudayang** [SharmisthaJat/RE-DS-Word-Attention-Models#5]
hello, can you send me the auc of pr curve of model BGWA? I need this data to use in my paper.

**Comment by SharmisthaJat** [comment]
Hi, 

All PR files are provided in the link mentioned at the bottom of project Readme page. Providing it here as well, link: https://www.dropbox.com/s/69j59s81d8bxaa5/RE-best-models.zip?dl=0 

Let me know if you need any other information. Goodluck!
